# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull Request Check

env:
  APP_NAME: slack-notif-review
  REPO_NAME: github.com/4IP/slack-notif-review
  VERSION_GIT_COMMIT: $GITHUB_SHA
  BASE_BRANCH: ${{ github.head_ref }}
on:
  pull_request:
    types: [ opened, synchronize, ready_for_review ]
    branches: [ master, develop ]
  pull_request_review:
    types: [ submitted ]

jobs:
  notify:
    if: ${{ !github.event.pull_request.draft }}
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: 4IP/slack-notif-review@0.3
        env:
          IGNORE_DRAFTS: false # Ignore draft pull requests. Default: true.
          PR_APPROVED_FORMAT: | # Format is fully customizable.
            *{ pull_request.title }* was approved by { review.user.login } at PR { pull_request.html_url } :white_check_mark:
          PR_READY_FOR_REVIEW_FORMAT: |
            <!here> please review, Jamtangancom-web PR!!! :rocket: :sungkem:
            Title: *{ pull_request.title }*
            Author: { pull_request.user.login }
            URL: { pull_request.html_url }
          PR_COMMENTED_FORMAT: |
            *{ pull_request.title }* was commented by { review.user.login } at PR { pull_request.html_url } :write_hand:
          PR_REJECTED_FORMAT: |
            *{ pull_request.title }* was rejected by { review.user.login } :cry:
          SLACK_CHANNEL: testing-ariefjr
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          USERNAME: Denjiro
